#!/bin/dash
# Main function: Initialize a .shrug directory

# warn if shrug-init is given command line args
if [ $# -gt 0 ]
then 
    echo "usage: "$0""
    exit 1
fi

# warn if .shrug file already exists
if test -d ".shrug"
then 
    echo ""$0": error: .shrug already exists" # always use $0 for filename
    exit 1
    
else 
    # create a main dir called .shrug 
    # and sub dir called index as a staging area
    mkdir .shrug
    mkdir .shrug/index
    echo "Initialized empty shrug repository in .shrug"
fi 