#!/bin/dash
# Main function: Add files from current working directory to index

# check validity of argument/files
checkArgs() {
    for f in "$@"
    do
        # check if filename is alphanumeric or has special chars - _ .
        if echo "$f" | grep -E "[^A-Za-z0-9._-]"  > /dev/null  
        then
            echo ""$0": error: invalid filename '"$f"'"
            exit 1
        fi
        
        # if file is absent in current dir....
        if ! test -e "$f" 
        then 
            # ..and also absent in the index, send error message 
            if ! test -e .shrug/index/"$f"
            then
                echo ""$0": error: can not open '"$f"'"
                exit 1
            else
                # if file is absent in curr dir, 
                # but present in index,
                # we need to delete it 
                continue
            fi
        fi

        # check if its a regular file
        if ! test -f "$f" 
        then
            echo ""$0": error: '"$f"' is not a regular file"
            exit 1
        fi
        
    done
}

# copy files from working dir to index
copyFiles() {
    for f in "$@"
    do
        # if the file is absent in current dir...
        if ! test -e "$f" 
        then 
            # ..but present in the index - delete it from index 
            if test -e .shrug/index/"$f"
            then
                rm .shrug/index/"$f"
                continue
            fi
        fi
        # otherwise copy
        cp "$f" .shrug/index/
    done
}

####### Main function starts here ########

# Checks if .shrug dir exists
if ! test -d ".shrug"
then 
    echo ""$0": error: no .shrug directory containing shrug repository exists"
    exit 1
fi

# Checks if no args are given
if [ "$#" -eq 0 ]
then
    echo "usage: "$0" <filenames>"
    exit 1
fi

checkArgs "$@"

copyFiles "$@"




